# Filtering and Sorting

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students_dataset.csv')

In [3]:
df

   First_Name  Last_Name  Roll_Number  Total_Marks Section
0       Rahul     Mathur            1          480       B
1   Aishwarya      Mehta            2          269       B
2       Vivek       Bose            3          418       A
3       Varun      Reddy            4          392       B
4       Komal     Pandey            5          303       A
5       Komal      Gupta            6          500       B
6       Sonam  Chowdhury            7          484       A
7      Vikram      Salvi            8          400       C
8        Yash   Deshmukh            9          207       B
9       Manav  Chowdhury           10          422       B
10       Isha     Pandey           11          437       C
11     Ashwin   Deshmukh           12          270       B
12      Akash   Tripathi           13          423       B
13      Nisha      Menon           14          399       C
14      Priya      Kohli           15          414       B
15     Simran   Deshmukh           16          375       C
16      Sanya      Naidu           17          253       C
17      Rohan     Thakur           18          435       C
18      Rahul     Mathur           19          439       C
19     Ashwin   Deshmukh           20          279       B
20       Diya      Salvi           21          200       A
21        Raj       Nair           22          223       B
22     Ananya     Chopra           23          367       C
23     Ananya      Patel           24          402       C
24     Pranav     Mathur           25          337       B
25      Tanya      Salvi           26          224       C
26      Kunal      Ghosh           27          286       C
27     Vikram      Kohli           28          465       B
28      Komal       Nair           29          479       A
29      Akash      Kohli           30          273       B
30      Tanvi      Dutta           31          416       C
31      Priya      Hooda           32          208       B
32  Siddharth      Singh           33          224       C
33      Akash       Bhat           34          247       B
34     Aditya       Bose           35          322       A
35     Naveen      Joshi           36          470       C
36      Vivek     Thakur           37          459       B
37      Tanya      Verma           38          345       B
38      Meera      Kohli           39          451       B
39     Pranav      Ahuja           40          367       A
40        Raj     Thakur           41          498       A
41      Komal      Rawat           42          492       A
42      Komal      Salvi           43          479       A
43      Rohan      Sethi           44          388       B
44      Sonam      Gupta           45          315       C
45      Priya     Sharma           46          416       B
46       Isha       Bose           47          406       A
47       Ravi      Verma           48          292       A
48      Kiran      Naidu           49          366       C
49      Kiran      Singh           50          312       A

In [20]:
k = (df["Last_Name"]=="Kohli")
df.loc[k]

   First_Name  Last_Name  Roll_Number  Total_Marks Section
0       Rahul     Mathur            1          480       B
1   Aishwarya      Mehta            2          269       B
2       Vivek       Bose            3          418       A
3       Varun      Reddy            4          392       B
4       Komal     Pandey            5          303       A
5       Komal      Gupta            6          500       B
6       Sonam  Chowdhury            7          484       A
7      Vikram      Salvi            8          400       C
8        Yash   Deshmukh            9          207       B
9       Manav  Chowdhury           10          422       B
10       Isha     Pandey           11          437       C
11     Ashwin   Deshmukh           12          270       B
12      Akash   Tripathi           13          423       B
13      Nisha      Menon           14          399       C
15     Simran   Deshmukh           16          375       C
16      Sanya      Naidu           17          253       C
17      Rohan     Thakur           18          435       C
18      Rahul     Mathur           19          439       C
19     Ashwin   Deshmukh           20          279       B
20       Diya      Salvi           21          200       A
21        Raj       Nair           22          223       B
22     Ananya     Chopra           23          367       C
23     Ananya      Patel           24          402       C
24     Pranav     Mathur           25          337       B
25      Tanya      Salvi           26          224       C
26      Kunal      Ghosh           27          286       C
28      Komal       Nair           29          479       A
30      Tanvi      Dutta           31          416       C
31      Priya      Hooda           32          208       B
32  Siddharth      Singh           33          224       C
33      Akash       Bhat           34          247       B
34     Aditya       Bose           35          322       A
35     Naveen      Joshi           36          470       C
36      Vivek     Thakur           37          459       B
37      Tanya      Verma           38          345       B
39     Pranav      Ahuja           40          367       A
40        Raj     Thakur           41          498       A
41      Komal      Rawat           42          492       A
42      Komal      Salvi           43          479       A
43      Rohan      Sethi           44          388       B
44      Sonam      Gupta           45          315       C
45      Priya     Sharma           46          416       B
46       Isha       Bose           47          406       A
47       Ravi      Verma           48          292       A
48      Kiran      Naidu           49          366       C
49      Kiran      Singh           50          312       A

In [19]:
df.loc[k,["First_Name","Last_Name","Roll_Number"]]

   First_Name Last_Name  Roll_Number
14      Priya     Kohli           15
27     Vikram     Kohli           28
29      Akash     Kohli           30
38      Meera     Kohli           39

In [16]:
k = (df["Last_Name"]!="Kohli")
df.loc[k]

   First_Name  Last_Name  Roll_Number  Total_Marks Section
0       Rahul     Mathur            1          480       B
1   Aishwarya      Mehta            2          269       B
2       Vivek       Bose            3          418       A
3       Varun      Reddy            4          392       B
4       Komal     Pandey            5          303       A
5       Komal      Gupta            6          500       B
6       Sonam  Chowdhury            7          484       A
7      Vikram      Salvi            8          400       C
8        Yash   Deshmukh            9          207       B
9       Manav  Chowdhury           10          422       B
10       Isha     Pandey           11          437       C
11     Ashwin   Deshmukh           12          270       B
12      Akash   Tripathi           13          423       B
13      Nisha      Menon           14          399       C
15     Simran   Deshmukh           16          375       C
16      Sanya      Naidu           17          253       C
17      Rohan     Thakur           18          435       C
18      Rahul     Mathur           19          439       C
19     Ashwin   Deshmukh           20          279       B
20       Diya      Salvi           21          200       A
21        Raj       Nair           22          223       B
22     Ananya     Chopra           23          367       C
23     Ananya      Patel           24          402       C
24     Pranav     Mathur           25          337       B
25      Tanya      Salvi           26          224       C
26      Kunal      Ghosh           27          286       C
28      Komal       Nair           29          479       A
30      Tanvi      Dutta           31          416       C
31      Priya      Hooda           32          208       B
32  Siddharth      Singh           33          224       C
33      Akash       Bhat           34          247       B
34     Aditya       Bose           35          322       A
35     Naveen      Joshi           36          470       C
36      Vivek     Thakur           37          459       B
37      Tanya      Verma           38          345       B
39     Pranav      Ahuja           40          367       A
40        Raj     Thakur           41          498       A
41      Komal      Rawat           42          492       A
42      Komal      Salvi           43          479       A
43      Rohan      Sethi           44          388       B
44      Sonam      Gupta           45          315       C
45      Priya     Sharma           46          416       B
46       Isha       Bose           47          406       A
47       Ravi      Verma           48          292       A
48      Kiran      Naidu           49          366       C
49      Kiran      Singh           50          312       A

In [21]:
df.loc[~k,["First_Name","Last_Name","Roll_Number"]]

   First_Name  Last_Name  Roll_Number
0       Rahul     Mathur            1
1   Aishwarya      Mehta            2
2       Vivek       Bose            3
3       Varun      Reddy            4
4       Komal     Pandey            5
5       Komal      Gupta            6
6       Sonam  Chowdhury            7
7      Vikram      Salvi            8
8        Yash   Deshmukh            9
9       Manav  Chowdhury           10
10       Isha     Pandey           11
11     Ashwin   Deshmukh           12
12      Akash   Tripathi           13
13      Nisha      Menon           14
15     Simran   Deshmukh           16
16      Sanya      Naidu           17
17      Rohan     Thakur           18
18      Rahul     Mathur           19
19     Ashwin   Deshmukh           20
20       Diya      Salvi           21
21        Raj       Nair           22
22     Ananya     Chopra           23
23     Ananya      Patel           24
24     Pranav     Mathur           25
25      Tanya      Salvi           26
26      Kunal      Ghosh           27
28      Komal       Nair           29
30      Tanvi      Dutta           31
31      Priya      Hooda           32
32  Siddharth      Singh           33
33      Akash       Bhat           34
34     Aditya       Bose           35
35     Naveen      Joshi           36
36      Vivek     Thakur           37
37      Tanya      Verma           38
39     Pranav      Ahuja           40
40        Raj     Thakur           41
41      Komal      Rawat           42
42      Komal      Salvi           43
43      Rohan      Sethi           44
44      Sonam      Gupta           45
45      Priya     Sharma           46
46       Isha       Bose           47
47       Ravi      Verma           48
48      Kiran      Naidu           49
49      Kiran      Singh           50

In [25]:
k = (df["Last_Name"] == "Kohli") | (df["Last_Name"] == "Gupta")
df.loc[k]

   First_Name Last_Name  Roll_Number  Total_Marks Section
5       Komal     Gupta            6          500       B
14      Priya     Kohli           15          414       B
27     Vikram     Kohli           28          465       B
29      Akash     Kohli           30          273       B
38      Meera     Kohli           39          451       B
44      Sonam     Gupta           45          315       C

In [26]:
k = df["Last_Name"].isin(["Kohli", "Gupta"])
df.loc[k]

   First_Name Last_Name  Roll_Number  Total_Marks Section
5       Komal     Gupta            6          500       B
14      Priya     Kohli           15          414       B
27     Vikram     Kohli           28          465       B
29      Akash     Kohli           30          273       B
38      Meera     Kohli           39          451       B
44      Sonam     Gupta           45          315       C

#**Sorting**

In [32]:
df.sort_values(by="First_Name")

   First_Name  Last_Name  Roll_Number  Total_Marks Section
34     Aditya       Bose           35          322       A
1   Aishwarya      Mehta            2          269       B
12      Akash   Tripathi           13          423       B
29      Akash      Kohli           30          273       B
33      Akash       Bhat           34          247       B
22     Ananya     Chopra           23          367       C
23     Ananya      Patel           24          402       C
19     Ashwin   Deshmukh           20          279       B
11     Ashwin   Deshmukh           12          270       B
20       Diya      Salvi           21          200       A
46       Isha       Bose           47          406       A
10       Isha     Pandey           11          437       C
49      Kiran      Singh           50          312       A
48      Kiran      Naidu           49          366       C
41      Komal      Rawat           42          492       A
28      Komal       Nair           29          479       A
5       Komal      Gupta            6          500       B
4       Komal     Pandey            5          303       A
42      Komal      Salvi           43          479       A
26      Kunal      Ghosh           27          286       C
9       Manav  Chowdhury           10          422       B
38      Meera      Kohli           39          451       B
35     Naveen      Joshi           36          470       C
13      Nisha      Menon           14          399       C
39     Pranav      Ahuja           40          367       A
24     Pranav     Mathur           25          337       B
45      Priya     Sharma           46          416       B
14      Priya      Kohli           15          414       B
31      Priya      Hooda           32          208       B
0       Rahul     Mathur            1          480       B
18      Rahul     Mathur           19          439       C
40        Raj     Thakur           41          498       A
21        Raj       Nair           22          223       B
47       Ravi      Verma           48          292       A
43      Rohan      Sethi           44          388       B
17      Rohan     Thakur           18          435       C
16      Sanya      Naidu           17          253       C
32  Siddharth      Singh           33          224       C
15     Simran   Deshmukh           16          375       C
44      Sonam      Gupta           45          315       C
6       Sonam  Chowdhury            7          484       A
30      Tanvi      Dutta           31          416       C
25      Tanya      Salvi           26          224       C
37      Tanya      Verma           38          345       B
3       Varun      Reddy            4          392       B
27     Vikram      Kohli           28          465       B
7      Vikram      Salvi            8          400       C
36      Vivek     Thakur           37          459       B
2       Vivek       Bose            3          418       A
8        Yash   Deshmukh            9          207       B

In [33]:
df.sort_values(by="First_Name", ascending=False)

   First_Name  Last_Name  Roll_Number  Total_Marks Section
8        Yash   Deshmukh            9          207       B
2       Vivek       Bose            3          418       A
36      Vivek     Thakur           37          459       B
27     Vikram      Kohli           28          465       B
7      Vikram      Salvi            8          400       C
3       Varun      Reddy            4          392       B
37      Tanya      Verma           38          345       B
25      Tanya      Salvi           26          224       C
30      Tanvi      Dutta           31          416       C
6       Sonam  Chowdhury            7          484       A
44      Sonam      Gupta           45          315       C
15     Simran   Deshmukh           16          375       C
32  Siddharth      Singh           33          224       C
16      Sanya      Naidu           17          253       C
17      Rohan     Thakur           18          435       C
43      Rohan      Sethi           44          388       B
47       Ravi      Verma           48          292       A
21        Raj       Nair           22          223       B
40        Raj     Thakur           41          498       A
0       Rahul     Mathur            1          480       B
18      Rahul     Mathur           19          439       C
31      Priya      Hooda           32          208       B
45      Priya     Sharma           46          416       B
14      Priya      Kohli           15          414       B
39     Pranav      Ahuja           40          367       A
24     Pranav     Mathur           25          337       B
13      Nisha      Menon           14          399       C
35     Naveen      Joshi           36          470       C
38      Meera      Kohli           39          451       B
9       Manav  Chowdhury           10          422       B
26      Kunal      Ghosh           27          286       C
5       Komal      Gupta            6          500       B
4       Komal     Pandey            5          303       A
42      Komal      Salvi           43          479       A
41      Komal      Rawat           42          492       A
28      Komal       Nair           29          479       A
48      Kiran      Naidu           49          366       C
49      Kiran      Singh           50          312       A
10       Isha     Pandey           11          437       C
46       Isha       Bose           47          406       A
20       Diya      Salvi           21          200       A
11     Ashwin   Deshmukh           12          270       B
19     Ashwin   Deshmukh           20          279       B
23     Ananya      Patel           24          402       C
22     Ananya     Chopra           23          367       C
12      Akash   Tripathi           13          423       B
33      Akash       Bhat           34          247       B
29      Akash      Kohli           30          273       B
1   Aishwarya      Mehta            2          269       B
34     Aditya       Bose           35          322       A

In [34]:
df.sort_index(inplace=True)